### ISSUE TITLE
Wrong severity level is set when Core process is failed to start

### ISSUE THREAD

**Issue by astsiapanay** [epam/ai-dial-core#159]
The current level is WARN but it should be ERROR
See the log below:

```
2024-01-17 19:01:35.195 WARN [main] Proxy failed to start:
  java.lang.IllegalArgumentException: At least one identity provider is required
    at com.epam.aidial.core.security.AccessTokenValidator.<init>(AccessTokenValidator.java:25)
    at com.epam.aidial.core.AiDial.start(AiDial.java:76)
    at com.epam.aidial.core.AiDial.main(AiDial.java:208)
  2024-01-17 19:01:35.230 INFO [main] Proxy stopped
  Exception in thread "main" java.lang.IllegalArgumentException: At least one identity provider is required
    at com.epam.aidial.core.security.AccessTokenValidator.<init>(AccessTokenValidator.java:25)
    at com.epam.aidial.core.AiDial.start(AiDial.java:76)
    at com.epam.aidial.core.AiDial.main(AiDial.java:208)
```

**Comment by astsiapanay** [comment]
fixed by #185
