### ISSUE TITLE
Application does not terminate if severe error occurs

### ISSUE THREAD

**Issue by nepalevov** [epam/ai-dial-core#185]
I expect the app to exit process with non-zero exit code if any severe error occurs, e.g. which leads to log entry like `INFO [main] Proxy stopped`. At this moment, it doesn't, e.g. with invalid Redis configuration:

```log
2024-01-30 14:48:10.535 INFO [main] Redisson 3.25.1
2024-01-30 14:48:15.070 WARN [main] Proxy failed to start:
java.lang.IllegalArgumentException: At least one cluster node should be defined!
    at org.redisson.cluster.ClusterConnectionManager.doConnect(ClusterConnectionManager.java:86)
    at org.redisson.connection.MasterSlaveConnectionManager.connect(MasterSlaveConnectionManager.java:196)
    at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:220)
    at org.redisson.Redisson.<init>(Redisson.java:65)
    at org.redisson.Redisson.create(Redisson.java:110)
    at com.epam.aidial.core.AiDial.openRedis(AiDial.java:126)
    at com.epam.aidial.core.AiDial.start(AiDial.java:95)
    at com.epam.aidial.core.AiDial.main(AiDial.java:235)

2024-01-30 14:48:15.093 INFO [main] Proxy stopped
Exception in thread "main" java.lang.IllegalArgumentException: At least one cluster node should be defined!
    at org.redisson.cluster.ClusterConnectionManager.doConnect(ClusterConnectionManager.java:86)
    at org.redisson.connection.MasterSlaveConnectionManager.connect(MasterSlaveConnectionManager.java:196)
    at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:220)
    at org.redisson.Redisson.<init>(Redisson.java:65)
    at org.redisson.Redisson.create(Redisson.java:110)
    at com.epam.aidial.core.AiDial.openRedis(AiDial.java:126)
    ```

**Comment by astsiapanay** [comment]
Reddison thread remains working after the client is failed to be created due to wrong connection settings. So that causes Java process keeps running and not terminated.
[Redisson issue](https://github.com/redisson/redisson/issues/5631)
