### ISSUE TITLE
Fix ShareApiTest to run on Windows 11

### ISSUE THREAD

**Issue by Oleksii-Klimov** [epam/ai-dial-core#371]
The ShareApiTest tests fail to start on Windows 11 with the following error:
```
2024-06-14 09:57:29.549 WARN [Test worker] Failed to resolve executable. exception: Unrecognized OS: windows 11
redis.embedded.exceptions.OsDetectionException: Unrecognized OS: windows 11
	at redis.embedded.util.OSDetector.getOS(OSDetector.java:25)
	at redis.embedded.util.OSArchitecture.detect(OSArchitecture.java:34)
	at redis.embedded.RedisExecProvider.get(RedisExecProvider.java:36)
	at redis.embedded.RedisServerExecProvider.get(RedisServerExecProvider.java:7)
	at redis.embedded.RedisServerBuilder.resolveConfAndExec(RedisServerBuilder.java:139)
	at redis.embedded.RedisServerBuilder.tryResolveConfAndExec(RedisServerBuilder.java:120)
	at redis.embedded.RedisServerBuilder.build(RedisServerBuilder.java:104)
	at com.epam.aidial.core.ResourceBaseTest.init(ResourceBaseTest.java:108)
```

**Comment by astsiapanay** [comment]
@Oleksii-Klimov the library(embedded Redis) supports only Linux and MacOS.
