### ISSUE TITLE
GCP Core deployment start to fail after some time

### ISSUE THREAD

**Issue by tataranovich** [epam/ai-dial-core#472]
We have GCP deployment of Core which is working fine for some time (around 5 minutes or so). After this time DIAL unable to process any prompt with the following error in Core log:
```
2024-09-06 08:18:49.008 WARN [vert.x-worker-thread-11] Failed to decompress provided input: Not in GZIP format
2024-09-06 08:18:49.017 ERROR [vert.x-worker-thread-11] Failed to convert payload to the object
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'minute': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 7]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2572)
        at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2598)
        at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2606)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:765)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:3018)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2052)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:780)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4992)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4898)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3848)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3816)
        at com.epam.aidial.core.util.ProxyUtil.convertToObject(ProxyUtil.java:245)
        at com.epam.aidial.core.util.ProxyUtil.convertToObject(ProxyUtil.java:260)
        at com.epam.aidial.core.limiter.RateLimiter.checkTokenLimit(RateLimiter.java:185)
        at com.epam.aidial.core.limiter.RateLimiter.checkLimit(RateLimiter.java:174)
        at com.epam.aidial.core.limiter.RateLimiter.lambda$limit$1(RateLimiter.java:81)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:840)

2024-09-06 08:18:49.018 ERROR [vert.x-eventloop-thread-1] Failed to handle deployment gemini-1.5-pro
java.lang.IllegalArgumentException: Provided payload do not match required schema
        at com.epam.aidial.core.util.ProxyUtil.convertToObject(ProxyUtil.java:254)
        at com.epam.aidial.core.util.ProxyUtil.convertToObject(ProxyUtil.java:260)
        at com.epam.aidial.core.limiter.RateLimiter.checkTokenLimit(RateLimiter.java:185)
        at com.epam.aidial.core.limiter.RateLimiter.checkLimit(RateLimiter.java:174)
        at com.epam.aidial.core.limiter.RateLimiter.lambda$limit$1(RateLimiter.java:81)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:840)

2024-09-06 08:18:49.018 WARN [vert.x-eventloop-thread-1] Responding with error. Trace: 64bcc83829080daa1afebaaedec36fda. Span: 4aefdec94ed1bd59. Status: INTERNAL_SERVER_ERROR. Body: Failed to process deployment: gemini-1.5-pro
```

After initial investigation we believe that issue is around limits functionality when Core is unable to properly read limits blob from the GCS bucket.

@astsiapanay created [branch](https://github.com/epam/ai-dial-core/tree/gcp-debug) to log content that was read from bucket. Log output is

```
2024-09-06 08:18:49.008 INFO [vert.x-worker-thread-11] blobToResult. Blob content as string -> minute":{"window":"MINUTE","sums":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,232,0,0,0,0,0,0,0,0,0,716,0,0,0,0,0,0,0,0,0,0,0,0,0],"sum":948,"start":1725609227,"end":1725609287},"day":{"window":"DAY","sums":[0,0,0,0,0,0,0,1008,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"sum":1008,"start":479312,"end":479336}}
```

At the same time blob in GCS bucket is fine

```
$ gcloud storage cat gs://gcp-test-dial/core/Users/117054032200553098637/limits/gemini-1.5-pro/tokens | gzip -dc
{"minute":{"window":"MINUTE","sums":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,232,0,0,0,0,0,0,0,0,0,716,0,0,0,0,0,0,0,0,0,0,0,0,0],"sum":948,"start":1725609227,"end":1725609287},"day":{"window":"DAY","sums":[0,0,0,0,0,0,0,1008,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"sum":1008,"start":479312,"end":479336}}
```

For some reason application is loosing first two symbols `{"`.

**Comment by tataranovich** [comment]
@astsiapanay I deployed Core from development branch and it's working fine for me.
